package com.soundist.core.database

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(tableName = "sounds") data class SoundEntity(@PrimaryKey val id: String, val name: String, val category: String, val assetUri: String, val defaultVolume: Float, val favorite: Boolean = false)
@Entity(tableName = "presets") data class PresetEntity(@PrimaryKey val id: String, val name: String, val tracksJson: String, val purposeLabel: String?, val builtIn: Boolean, val updatedAt: Long)
@Entity(tableName = "radio_stations") data class RadioEntity(@PrimaryKey val id: String, val name: String, val streamUri: String, val artworkUri: String?, val favorite: Boolean = false, val description: String, val sourceKind: String, val genre: String, val purpose: String, val position: Double, val enabled: Boolean, val updatedAt: Long, val payloadJson: String? = null)
@Entity(tableName = "playback_snapshot") data class PlaybackEntity(@PrimaryKey val key: String = "current", val tracksJson: String, val radioId: String?, val playing: Boolean, val masterVolume: Float, val ambientVolume: Float, val radioVolume: Float, val radioTrackIndex: Int = 0, val updatedAt: Long)
@Entity(tableName = "focus_sessions", indices = [Index("targetKind", "targetId"), Index("startedAt")]) data class FocusSessionEntity(@PrimaryKey val id: String, val kind: String, val status: String, val startedAt: Long, val targetEndAt: Long?, val pausedAt: Long?, val completedAt: Long?, val label: String?, val targetKind: String, val targetId: String?, val timerMode: String, val elapsedSeconds: Long, val review: String?, val soundSnapshotJson: String, val radioSnapshotId: String?, val phase: String = "FOCUS", val focusMinutes: Int = 25, val breakMinutes: Int = 5, val cycleRound: Int = 1, val cycleRounds: Int = 4, val longBreakMinutes: Int = 15, val autoBreak: Boolean = true, val autoFocus: Boolean = false, val completionMinutes: Int = 0, val ambientMode: String? = null, val audioSource: String = "UNRECORDED")
@Entity(tableName = "todos", indices = [Index("planId"), Index("dueAt")]) data class TodoEntity(@PrimaryKey val id: String, val title: String, val completed: Boolean, val dueAt: Long?, val updatedAt: Long, val longTerm: Boolean, val allDay: Boolean, val priority: String, val reminderAt: Long?, val estimatedMinutes: Int?, val planId: String?, val note: String, val defaultSceneId: String?, val archived: Boolean, val position: Double)
@Entity(tableName = "plans") data class PlanEntity(@PrimaryKey val id: String, val title: String, val startAt: Long, val endAt: Long?, val updatedAt: Long, val targetMinutes: Int, val accumulatedMinutes: Int, val milestone: String, val description: String, val reminderAt: Long?, val defaultSceneId: String?, val archived: Boolean, val position: Double)
@Entity(tableName = "habits") data class HabitEntity(@PrimaryKey val id: String, val name: String, val targetPerWeek: Int, val updatedAt: Long, val weekdaysJson: String, val metric: String, val dailyTarget: Int, val streak: Int, val reminderAt: Long?, val defaultSceneId: String?, val archived: Boolean, val position: Double, val reminderHour: Int = 9, val reminderMinute: Int = 0)
@Entity(tableName = "habit_checks", indices = [Index("habitId"), Index("checkedAt")]) data class HabitCheckEntity(@PrimaryKey val id: String, val habitId: String, val checkedAt: Long, val value: Int)
@Entity(tableName = "countdowns") data class CountdownEntity(@PrimaryKey val id: String, val title: String, val targetAt: Long, val updatedAt: Long, val note: String, val dailyMinutes: Int, val investedMinutes: Int, val planId: String?, val milestone: String, val reminderAt: Long?, val archived: Boolean, val position: Double)
@Entity(tableName = "sleep_routines") data class SleepRoutineEntity(@PrimaryKey val id: String, val name: String, val minutes: Int, val target: String, val fadeMinutes: Int, val endMode: String, val clockTime: String?, val sceneId: String?, val enabled: Boolean, val updatedAt: Long)
@Entity(tableName = "sleep_sessions", indices = [Index("startedAt")]) data class SleepSessionEntity(@PrimaryKey val id: String, val startedAt: Long, val targetEndAt: Long, val actualEndAt: Long?, val target: String, val fadeMinutes: Int, val status: String, val routineId: String?, val volumeSnapshotCaptured: Boolean = false, val masterVolumeSnapshot: Float = 1f, val ambientVolumeSnapshot: Float = 1f, val radioVolumeSnapshot: Float = .8f)
@Entity(tableName = "notebooks") data class NotebookEntity(@PrimaryKey val id: String, val title: String, val updatedAt: Long, val position: Double, val accent: Long = 0xFF7F8C87, val iconKey: String = "bookOpen")
@Entity(tableName = "notes", indices = [Index("notebookId"), Index("updatedAt")]) data class NoteEntity(@PrimaryKey val id: String, val notebookId: String?, val title: String, val body: String, val archived: Boolean = false, val deletedAt: Long?, val updatedAt: Long, val createdAt: Long, val pinned: Boolean, val tagsJson: String, val originalNotebookId: String?, val position: Double)
@Entity(tableName = "note_blocks", indices = [Index("noteId")]) data class NoteBlockEntity(@PrimaryKey val id: String, val noteId: String, val kind: String, val text: String, val checked: Boolean, val assetId: String?, val linkedNoteId: String?, val position: Double, val revision: Long)
@Entity(tableName = "attachments", indices = [Index("noteId")]) data class AttachmentEntity(@PrimaryKey val id: String, val noteId: String, val mimeType: String, val localUri: String, val remotePath: String?, val updatedAt: Long, val kind: String, val displayName: String, val sizeBytes: Long, val durationSeconds: Long?, val width: Int?, val height: Int?, val thumbnailUri: String?, val checksum: String?, val uploadState: String)
@Entity(tableName = "playback_events", indices = [Index("startedAt"), Index("kind", "sourceId")]) data class PlaybackEventEntity(@PrimaryKey val id: String, val kind: String, val sourceId: String, val startedAt: Long, val endedAt: Long?, val activeSeconds: Long, val completed: Boolean, val trackId: String? = null, val sourceKind: String? = null, val listenedMs: Long = 0, val completionReason: String? = null)
@Entity(tableName = "custom_radio_files", indices = [Index("stationId")]) data class CustomRadioFileEntity(@PrimaryKey val id: String, val stationId: String, val displayName: String, val privatePath: String, val mimeType: String, val sizeBytes: Long, val durationMs: Long, val sha256: String, val sortIndex: Int)
@Entity(tableName = "sync_queue", indices = [Index(value = ["entityType", "entityId"], unique = true), Index(value = ["operationId"], unique = true), Index("state")]) data class SyncQueueEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val entityType: String, val entityId: String, val operation: String, val payload: String?, val operationId: String, val baseRevision: Long?, val clientUpdatedAt: Long, val state: String = "PENDING", val attempts: Int = 0, val nextAttemptAt: Long = 0, val lastError: String? = null, val createdAt: Long = System.currentTimeMillis())
@Entity(tableName = "sync_conflicts", indices = [Index("userId"), Index("entityType", "entityId")]) data class SyncConflictEntity(@PrimaryKey val operationId: String, val userId: String, val entityType: String, val entityId: String, val localPayload: String?, val remotePayload: String?, val localBaseRevision: Long?, val remoteRevision: Long, val remoteDeleted: Boolean, val recordedAt: Long)
@Entity(tableName = "sync_cursors") data class SyncCursorEntity(@PrimaryKey val userId: String, val cursor: String, val updatedAt: Long)
@Entity(tableName = "sync_revisions", primaryKeys = ["entityType", "entityId"], indices = [Index("revision")]) data class SyncRevisionEntity(val entityType: String, val entityId: String, val revision: Long, val deleted: Boolean, val serverUpdatedAt: Long)
